services:
  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: lendup
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - lendup_data:/var/lib/mysql
volumes:
  lendup_data:
