# Shared application settings
spring.application.name=LendUp
spring.profiles.default=dev
server.port=${PORT:8080}

spring.sql.init.mode=always
springdoc.swagger-ui.path=/swagger-ui.html




# Each incident can include up to six photos.
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=32MB
